// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	UserEmail    string `json:"user_email"`
	UserPassword string `json:"user_password"`
}

type Product struct {
	UserID       *string `json:"UserId"`
	ProductID    *string `json:"ProductId"`
	ProductName  *string `json:"ProductName"`
	ProductStock *int    `json:"ProductStock"`
	ProductPrice *int    `json:"ProductPrice"`
	CreatedDate  *string `json:"CreatedDate"`
	LastUpdate   *string `json:"LastUpdate"`
}

type Register struct {
	UserEmail    string `json:"user_email"`
	UserName     string `json:"user_name"`
	UserPassword string `json:"user_password"`
}

type ResponseLogin struct {
	User    *User   `json:"user"`
	Status  *int    `json:"status"`
	Message *string `json:"message"`
}

type ResponseRegister struct {
	Error   *string `json:"error"`
	Status  *int    `json:"status"`
	Message *string `json:"message"`
}

type User struct {
	UserID      *string    `json:"user_id"`
	UserEmail   *string    `json:"user_email"`
	UserName    *string    `json:"user_name"`
	UserImage   *string    `json:"user_image"`
	UserStatus  *string    `json:"user_status"`
	CreatedDate *string    `json:"created_date"`
	LastUpdate  *string    `json:"last_update"`
	Products    []*Product `json:"products"`
}
